# Generated by Django 3.2 on 2021-10-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('bio', models.TextField()),
                ('dob', models.DateField()),
                ('type', models.CharField(choices=[('actor', 'actor'), ('director', 'director')], max_length=10)),
            ],
            options={
                'verbose_name': 'Celebrity',
                'verbose_name_plural': 'Celebrities',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('release_date', models.DateField()),
                ('rated', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('R', 'R'), ('PG-13', 'PG-13'), ('NR', 'NR')], max_length=20)),
                ('is_prime', models.BooleanField(default=True)),
                ('length', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('synopsis', models.TextField()),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('movie', models.ManyToManyField(to='movies.Movies')),
                ('user', models.ManyToManyField(to='movies.Users')),
            ],
            options={
                'verbose_name': 'RecentlyViewedMovie',
                'verbose_name_plural': 'RecentlyViewedMovies',
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewedCeleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celeb', models.ManyToManyField(to='movies.Celebrity')),
                ('user', models.ManyToManyField(to='movies.Users')),
            ],
            options={
                'verbose_name': 'RecentlyViewedCeleb',
                'verbose_name_plural': 'RecentlyViewedCelebs',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('movie', models.ManyToManyField(to='movies.Movies')),
                ('user', models.ManyToManyField(to='movies.Users')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='MovieTrailers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'verbose_name': 'MovieTrailer',
                'verbose_name_plural': 'MovieTrailers',
            },
        ),
        migrations.CreateModel(
            name='MovieImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_trailer', models.BooleanField(default=True)),
                ('trailer', models.FileField(upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'verbose_name': 'MovieImage',
                'verbose_name_plural': 'MovieImages',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('movies', models.ManyToManyField(to='movies.Movies')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('movie', models.ManyToManyField(to='movies.Movies')),
                ('user', models.ManyToManyField(to='movies.Users')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='BookmarkedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('movie', models.ManyToManyField(related_name='users', to='movies.Movies')),
                ('user', models.ManyToManyField(related_name='movies', to='movies.Users')),
            ],
            options={
                'verbose_name': 'BookmarkedMovie',
                'verbose_name_plural': 'BookmarkedMovies',
            },
        ),
        migrations.CreateModel(
            name='AssociatedMoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celeb', models.ManyToManyField(to='movies.Celebrity')),
                ('movie', models.ManyToManyField(to='movies.Movies')),
            ],
            options={
                'verbose_name': 'AssociatedMovie',
                'verbose_name_plural': 'AssociatedMovies',
            },
        ),
    ]
